[build]
  command = "npm --prefix frontend ci || npm --prefix frontend i && npm --prefix frontend run build"
  publish = "frontend/dist"

[functions]
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "snapshot-write"
  schedule = "*/15 * * * *"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
